DIR: 
  exp: "testYaml"
  snapshot: "/Users/brian96086/Documents/DSC180/RL_Opt_Replication/ckpt"

SIMULATOR:
  population: 10000
  node_count: 100
  sim_type: "naive_seir"

MODEL:
  backbone: "deepQ"

TRAIN:
  episode: 100
  resume: "checkpoint_000000"
  

